#+TITLE: Explosives and Distinguishers
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="myStyle.css" />
#+OPTIONS: html-style:nil H:1 num:nil
/*Abstract.* I examine the relationship between decidable equality,
inequality, and distinguishability in the minimal fragment of [[https://docs.racket-lang.org/pie/index.html][Pie]]. I
prove that the statement:/

#+begin_quote
/If ūĚźī admits decidable equality, then unequal terms of type ūĚźī are
distinguishable/
#+end_quote

/holds in Pie, its minimal fragment and its paraconsistent variant,
but with necessarily different notions of decidable equality.  An
auxiliary goal of this piece is to present formal proofs that
demonstrate the ways in which basic claims about decidability depend
on the principle of explosion./

*Quick Preamble:* This piece contains (too) many proofs in [[https://docs.racket-lang.org/pie/index.html][Pie]], a
simple, beautiful, but verbose dependently typed programming language.
Here's a small logical interface used throughout to make proofs more
readable:

#+begin_src lisp
  #lang pie

  (claim ‚ä• U)
  (define ‚ä• Absurd)

  (claim ‚ä§ U)
  (define ‚ä§ Trivial)

  (claim ¬¨ (‚Üí U U))
  (define ¬¨ (őĽ (A) (‚Üí A ‚ä•)))

  (claim ‚ąß (‚Üí U U U))
  (define ‚ąß (őĽ (A B) (Pair A B)))

  (claim ‚ą® (‚Üí U U U))
  (define ‚ą® (őĽ (A B) (Either A B)))

  (claim ‚ÜĒ (‚Üí U U U))
  (define ‚ÜĒ (őĽ (A B) (‚ąß (‚Üí A B) (‚Üí B A))))

  (claim ‚Č† (ő† ((A U)) (‚Üí A A U)))
  (define ‚Č† (őĽ (A x y) (¬¨ (= A x y))))
#+end_src

*Preamble over.*

I recently spent an inordinate amount of time thinking about
Pie[fn::If only the sentence ended there.]  formalizations of the
following theorem:

#+begin_quote
/1 = 0 implies I am the Pope./
#+end_quote

I was interested primarily in proofs that could be carried out in the
minimal fragment of Pie, i.e., without the use of [[https://docs.racket-lang.org/pie/index.html#%28def._%28%28lib._pie%2Fmain..rkt%29._ind-.Absurd%29%29][~ind-Absurd~]], the
induction principle for the empty type which expresses the [[https://en.wikipedia.org/wiki/Principle_of_explosion][principle
of explosion]].  I'll call this fragment *minimal Pie* throughout, and
will try to use *vanilla Pie* otherwise for emphasis.

Thinking about this problem long enough leads invariably to a standard
fact of constructive mathematics: 1 = 0 is /explosive/ in the sense
that anything follows from it in minimal Pie.[fn::See, e.g., Proposition 3.2
of Constructivism in Mathematics by Trolestra and van Dalen.]

#+begin_src lisp
  (claim explode-1=0
    (‚Üí (= Nat 1 0) (ő† ((A U)) A)))
  (define explode-1=0
    (őĽ (1=0 A)
       (replace
         1=0
         (őĽ (a) (which-Nat a A (őĽ (_) ‚ä§)))
         sole)))
#+end_src

Thinking about this problem for too long leads to a natural enough
question: /which equalities are explosive?/

* Distinguishers

Its straightforward to generalize the above proof to any fixed pair of
natural numbers.

#+begin_src
  (claim sub1 (‚Üí Nat Nat))
  (define sub1
    (őĽ (n)
       (which-Nat n 0 (őĽ (n-1) n-1))))

  (claim ‚ął (‚Üí Nat Nat Nat))
  (define ‚ął
    (őĽ (m n)
       (iter-Nat n m sub1)))

  (claim 5=7‚Üí1=0
    (‚Üí (= Nat 5 7) (= Nat 1 0)))
  (define 5=7‚Üí1=0
    (őĽ (5=7)
       (symm
         (cong
           5=7
  	 (the
  	   (‚Üí Nat Nat)
  	   (őĽ (n) (‚ął n 6)))))))

  (claim explode-5=7
    (‚Üí (= Nat 5 7) (ő† ((A U)) A)))
  (define explode-5=7
    (őĽ (5=7)
       (explode-1=0 (5=7‚Üí1=0 5=7))))
#+end_src

It also works for the equality true = false, given the standard sum
type encoding of Booleans.

#+begin_src lisp
  (claim Bool U)
  (define Bool (Either ‚ä§ ‚ä§))

  (claim true Bool)
  (define true (left sole))

  (claim false Bool)
  (define false (right sole))

  (claim ind-Bool
    (ő† ((target Bool)
        (motive (‚Üí Bool U))
        (true-case (motive true))
        (false-case (motive false)))
       (motive target)))
  (define ind-Bool
    (őĽ (target motive true-case false-case)
       (ind-Either
         target
         motive
         (őĽ (_) true-case)
         (őĽ (_) false-case))))

  (claim bool‚Üínat (‚Üí Bool Nat))
  (define bool‚Üínat
    (őĽ (b) (ind-Bool b (őĽ (_) Nat) 1 0)))

  (claim true=false‚Üí1=0
    (‚Üí (= Bool true false) (= Nat 1 0)))
  (define true=false‚Üí1=0
    (őĽ (true=false) (cong true=false bool‚Üínat)))

  (claim explode-true=false
    (‚Üí (= Bool true false) (ő† ((A U)) A)))
  (define explode-true=false
    (őĽ (true=false)
       (explode-1=0 (true=false‚Üí1=0 true=false))))
#+end_src

All we're doing here is bootstrapping; if an equality implies 1 = 0
then it's explosive.  This condition is clunky, but it hints at a
definition: let's say a Boolean function ūĚĎď /distinguishes/ two values
ūĚĎé and ūĚĎŹ if ūĚĎď(ūĚĎé) is true and ūĚĎď(ūĚĎŹ) is false.  Let's also say ūĚĎé and ūĚĎŹ are
/distinguishable/, written ūĚĎé ‚óá ūĚĎŹ, if there is a distinguisher for
them.

#+begin_src lisp
  (claim Distinguishes
    (ő† ((A U)
        (f (‚Üí A Bool)))
       (‚Üí A A U)))
  (define Distinguishes
    (őĽ (_ f x y)
       (‚ąß (= Bool (f x) true)
          (= Bool (f y) false))))

  (claim ‚óá
    (ő† ((A U))
       (‚Üí A A U)))
  (define ‚óá
    (őĽ (A x y)
       (ő£ ((f (‚Üí A Bool)))
          (Distinguishes A f x y))))

  ; these are just getters for ‚óá

  (claim distinguisher-‚óá
    (ő† ((A U)
        (x A)
        (y A)
        (x‚óáy (‚óá A x y)))
       (‚Üí A Bool)))
  (define distinguisher-‚óá
    (őĽ (_ _ _ x‚óáy)
       (car x‚óáy)))

  (claim distinguishes-fst
    (ő† ((A U)
        (x A)
        (y A)
        (x‚óáy (‚óá A x y)))
       (= Bool
          (distinguisher-‚óá A x y x‚óáy x)
          true)))
  (define distinguishes-fst
    (őĽ (_ _ _ x‚óáy)
       (car (cdr x‚óáy))))

  (claim distinguishes-snd
    (ő† ((A U)
        (x A)
        (y A)
        (x‚óáy (‚óá A x y)))
       (= Bool
          (distinguisher-‚óá A x y x‚óáy y)
          false)))
  (define distinguishes-snd
    (őĽ (_ _ _ x‚óáy)
       (cdr (cdr x‚óáy))))
#+end_src

Distinguishability captures more generally what's going on in the
case of 5 = 7 and true = false.

#+begin_src lisp
  (claim ‚óá‚Üíexplode‚Āľ
    (ő† ((A U)
        (x A)
        (y A))
       (‚Üí (‚óá A x y)
          (= A x y)
          (ő† ((B U)) B))))
  (define ‚óá‚Üíexplode‚Āľ
    (őĽ (A x y x‚óáy x=y)
      (explode-true=false
        (trans
          ; true = f x
          (symm (distinguishes-fst A x y x‚óáy))
          (trans
            ; f x = f y
            (cong x=y (distinguisher-‚óá A x y x‚óáy))
            ; f y = false
            (distinguishes-snd A x y x‚óáy))))))
#+end_src

In other words, /any equality of distinguishable terms is explosive./

* Inequality

Distinguishability is a strictly stronger relation than inequality
minimal Pie.[fn::Moving forward, we'll take advantage of the fact that
the principle of explosion is not a theorem of minimal Pie: to show
that any other claim is not a theorem, it suffices to show that it
implies explosion.]

#+begin_src lisp
  (claim ‚óá‚Üí‚Č†
    (ő† ((A U)
        (x A)
        (y A))
       (‚Üí (‚óá A x y)
          (‚Č† A x y))))
  (define ‚óá‚Üí‚Č†
    (őĽ (A x y x‚óáy x=y)
       (‚óá‚Üíexplode‚Āľ A x y x‚óáy x=y ‚ä•)))

  (claim ‚ü®‚Č†‚Üí‚óá‚ü©‚Üíind-‚ä•
    (‚Üí (ő† ((A U)
           (x A)
           (y A))
          (‚Üí (‚Č† A x y)
             (‚óá A x y)))
       (‚Üí ‚ä• (ő† ((A U)) A))))
  (define ‚ü®‚Č†‚Üí‚óá‚ü©‚Üíind-‚ä•
    (őĽ (‚Č†‚Üí‚óá absurd)
       (‚óá‚Üíexplode‚Āľ
         ‚ä§
         sole
         sole
         (‚Č†‚Üí‚óá
           ‚ä§
  	 sole
  	 sole
  	 (őĽ (_) absurd))
         (same sole))))
#+end_src

‚Č†‚Üí‚óá has the flavor of many semi-classical principles: it expresses
that we can extract something constructive from a negation
proof.[fn::See, e.g., Proposition 2.1.1 in [[https://arxiv.org/abs/1804.05495][Constructive Reverse
Mathematics]] by Diener. Actually, just read the whole thing, it's very
good.]  So it's not surprising that we can't prove ‚Č†‚Üí‚óá in vanilla
Pie[fn::Said another way, we can't prove ind-‚ä•‚Üí‚Č†‚Üí‚óá in minimal Pie.]
but we also can't disprove it.  This is because ‚Č†‚Üí‚óá is a theorem in
the classical extension of Pie (which is consistent).[fn::Naturally,
I'll call this classical Pie.]

That ‚Č†‚Üí‚óá holds classically is not immediately obivous, but becomes
more clear through the lens of [[https://ncatlab.org/nlab/show/decidable%20equality][decidable equality]].  In vanilla Pie,
*if ūĚźī admits decidable equality, then unequal terms of type ūĚźī are
distinguishable.*

And how does /that/ work?  This is also not immediately obvious.  It's
easy to forget that decidability, though core to constructive type
theory, has its origins in computability theory.

* Decidability

A type ūĚźī admits *decidable equality* if for any two terms ūĚĎé‚āĀ and ūĚĎé‚āā of
type ūĚźī, we have ūĚĎé‚āĀ = ūĚĎé‚āā or ūĚĎé‚āĀ ‚Č† ūĚĎé‚āā.  This is a restriction of the [[https://en.wikipedia.org/wiki/Law_of_excluded_middle][law
of excluded middle]], so all types admit decidable equality in classical
Pie.

The computability theoretic notion of decidability is slightly
different: a predicate ūĚĎÉ is *decidable* if there is a computable
function ūĚĎď such that ūĚĎď(ūĚĎ•) = 1 if and only if ūĚĎÉ(ūĚĎ•) holds.

/How do these two notions correspond?/ We just need to put on our
[[https://en.wikipedia.org/wiki/Curry‚ÄďHoward_correspondence][Curry-Howard]] glasses: a term ūĚĎď of type

#+begin_quote
(ő† ((ūĚĎ• ūĚźī) (ūĚĎ• ūĚźī)) (‚ą® (= ūĚźī ūĚĎ• ūĚĎ¶) (‚Č† ūĚźī ūĚĎ• ūĚĎ¶)))
#+end_quote

on the one hand is a proof that ūĚźī admits decidable equality.  On the
other hand, it's a /computable function/ where ūĚĎď(ūĚĎé, ūĚĎŹ) evaluates to a
left term if ūĚĎé = ūĚĎŹ and a right term otherwise.  Since we can determine
leftness versus rightness programmatically (using [[https://docs.racket-lang.org/pie/index.html#%28def._%28%28lib._pie%2Fmain..rkt%29._ind-.Either%29%29][~ind-Either~]]), the
term ūĚĎď can be made an equality decider in the computability theoretic
sense.

More generally, a type ūĚźī (viewed through the Curry-Howard lens) is
*decidable* if either ūĚźī or ¬¨ūĚźī holds.  The law of excluded middle is
equivalent to every type being decidable.  We can lift this notion of
decidability to binary predicates, but if we want to use those
predicates in their Curried form, we'll need to uncurry when reasoning
about their decidability.[fn::If I were building an interface for
decidability in Pie, I would /not/ design it this way, but this makes
proving things easier: there's no need to do intermediate translations
between equivalent definitions.]

#+begin_src
(claim Dec (‚Üí U U))
(define Dec
  (őĽ (A) (‚ą® A (¬¨ A))))

(claim DecŠīĺ
  (ő† ((A U)
      (P (‚Üí A U)))
     U))
(define DecŠīĺ
  (őĽ (A P)
     (ő† ((x A)) (Dec (P x)))))

(claim UncurryŠīĺ
  (ő† ((A U)
      (B U)
      (P (‚Üí A B U)))
     (‚Üí (Pair A B) U)))
(define UncurryŠīĺ
  (őĽ (_ _ P p)
     (P (car p) (cdr p))))

(claim DecŠīĺ¬≤
  (ő† ((A U)
      (B U)
      (P (‚Üí A B U)))
     U))
(define DecŠīĺ¬≤
  (őĽ (A B P)
     (DecŠīĺ (Pair A B) (UncurryŠīĺ A B P))))

(claim Dec‚Āľ (‚Üí U U))
(define Dec‚Āľ
  (őĽ (A)
     (DecŠīĺ¬≤
       A
       A
       (őĽ (x y) (= A x y)))))
#+end_src

We express the computability theoretic notion of decidability as
having a decider, i.e., a function that witnesses the truth value of
the predicate.

#+begin_src
(claim Decides
  (ő† ((A U)
      (f (‚Üí A Bool))
      (P (‚Üí A U)))
     U))
(define Decides
  (őĽ (A f P)
     (ő† ((x A))
        (‚ÜĒ (P x)
	   (= Bool (f x) true)))))

(claim Decider
  (ő† ((A U)
      (P (‚Üí A U)))
     U))
(define Decider
  (őĽ (A P)
     (ő£ ((f (‚Üí A Bool)))
        (Decides A f P))))

(claim uncurry
  (ő† ((A U)
      (B U)
      (C U))
     (‚Üí (‚Üí A B C)
        (‚Üí (Pair A B) C))))
(define uncurry
  (őĽ (_ _ _ f p)
     (f (car p) (cdr p))))

(claim Decides‚āā
  (ő† ((A U)
      (B U)
      (f (‚Üí A B Bool))
      (P (‚Üí A B U)))
     U))
(define Decides‚āā
  (őĽ (A B f P)
     (Decides
       (Pair A B)
       (uncurry A B Bool f)
       (UncurryŠīĺ A B P))))

(claim Decider‚āā
  (ő† ((A U)
      (B U)
      (P (‚Üí A B U)))
     U))
(define Decider‚āā
  (őĽ (A B P)
     (ő£ ((f (‚Üí A B Bool)))
        (Decides‚āā A B f P))))

(claim Decides‚Āľ
  (ő† ((A U)
      (f (‚Üí A A Bool)))
     U))
(define Decides‚Āľ
  (őĽ (A f)
     (Decides‚āā
       A
       A
       f
       (őĽ (x y) (= A x y)))))

(claim Decider‚Āľ (‚Üí U U))
(define Decider‚Āľ
  (őĽ (A)
     (ő£ ((f (‚Üí A A Bool)))
        (Decides‚Āľ A f))))
#+end_src

As noted above, types that admit decidable equalities have an
"obvious" decider, i.e., the one encoded in the proof of decidability.

#+begin_src
(claim left?
  (ő† ((A U)
      (B U))
     (‚Üí (Either A B)
        Bool)))
(define left?
  (őĽ (_ _ e)
     (ind-Either
       e
       (őĽ (_) Bool)
       (őĽ (_) true)
       (őĽ (_) false))))

(claim ?
  (ő† ((A U)
      (P (‚Üí A U)))
     (‚Üí (DecŠīĺ A P) A Bool)))
(define ?
  (őĽ (_ P decŠīĺ x)
     (left?
       (P x)
       (¬¨ (P x))
       (decŠīĺ x))))

(claim ?‚āā
  (ő† ((A U)
      (B U)
      (P (‚Üí A B U))
      (decŠīĺ¬≤ (DecŠīĺ¬≤ A B P)))
     (‚Üí A B Bool)))
(define ?‚āā
  (őĽ (A B P decŠīĺ¬≤ x y)
     (?
       (Pair A B)
       (UncurryŠīĺ A B P)
       decŠīĺ¬≤
       (cons x y))))

(claim ‚Čü
  (ő† ((A U))
     (‚Üí (Dec‚Āľ A) A A Bool)))
(define ‚Čü
  (őĽ (A) (?‚āā A A (őĽ (x y) (= A x y)))))
#+end_src

And we can convert the equality decider into an /distinguisher/ by
partially applying it: if ūĚĎď(ūĚĎé, ūĚĎŹ) is true if and only if ūĚĎé = ūĚĎŹ, then
if ūĚĎé ‚Č† ūĚĎŹ we have we (őĽūĚĎ•.ūĚĎď(ūĚĎé, ūĚĎ•))(ūĚĎé) is true and (őĽūĚĎ•.ūĚĎď(ūĚĎé, ūĚĎ•))(b) is
false.  But, our first "interesting" observation: that this holds
depends crucially on the principle of explosion.

#+begin_src lisp
(claim ind-‚ä•‚Üídec‚Āľ‚Üí‚Č†‚Üí‚óá
  (‚Üí (‚Üí ‚ä• (ő† ((A U)) A))
     (ő† ((A U)
         (dec‚Āľ (Dec‚Āľ A))
         (x A)
         (y A))
        (‚Üí (‚Č† A x y) (‚óá A x y)))))
(define ind-‚ä•‚Üídec‚Āľ‚Üí‚Č†‚Üí‚óá
  (őĽ (ind-‚ä• A dec‚Āľ x y x‚Č†y)
     (cons
       (‚Čü A dec‚Āľ x)
       (cons
         (ind-Either
	   (dec‚Āľ (cons x x))
	   (őĽ (e)
	      (= Bool
	         (left?
		   (= A x x)
		   (‚Č† A x x)
		   e)
		 true))
           (őĽ (_) (same true))
	   (őĽ (x‚Č†x)
	      (ind-‚ä•
	        (x‚Č†x (same x))
	        (= Bool false true))))
	 (ind-Either
	   (dec‚Āľ (cons x y))
	   (őĽ (e)
	      (= Bool
	         (left?
		   (= A x y)
		   (‚Č† A x y)
		   e)
		 false))
            (őĽ (x=y) (ind-‚ä• (x‚Č†y x=y) (= Bool true false)))
	    (őĽ (_) (same false)))))))

(claim ‚ü®dec‚Āľ‚Üí‚Č†‚Üí‚óá‚ü©‚Üíind-‚ä•
  (‚Üí (ő† ((A U)
         (dec‚Āľ (Dec‚Āľ A))
         (x A)
         (y A))
        (‚Üí (‚Č† A x y) (‚óá A x y)))
     (‚Üí ‚ä• (ő† ((A U)) A))))
(define ‚ü®dec‚Āľ‚Üí‚Č†‚Üí‚óá‚ü©‚Üíind-‚ä•
  (őĽ (dec‚Āľ‚Üí‚Č†‚Üí‚óá absurd)
     (‚óá‚Üíexplode‚Āľ
       ‚ä§
       sole
       sole
       (dec‚Āľ‚Üí‚Č†‚Üí‚óá
         ‚ä§
         (őĽ (_) (right (őĽ (_) absurd)))
         sole
         sole
         ; artificial negation proof
         (őĽ (_) absurd))
       (same sole))))
#+end_src

Another theme is made visible here: in nearly all cases, the ~Trivial~
type is sufficient to find a counterexample in minimal Pie of a given
principle.  And usually this comes down to an artificial proof of a
negation using our ~Absurd~ assumption (see above).

As a corollary, we can prove versions of ‚Č†‚Üí‚óá in classical Pie and
vanilla Pie.

#+begin_src lisp
  (claim dec‚Āľ‚Üí‚Č†‚Üí‚óá
    (ő† ((A U)
        (dec‚Āľ (Dec‚Āľ A))
        (x A)
        (y A))
       (‚Üí (‚Č† A x y) (‚óá A x y))))
  (define dec‚Āľ‚Üí‚Č†‚Üí‚óá
    (őĽ (A dec‚Āľ x y x‚Č†y)
       (ind-‚ä•‚Üídec‚Āľ‚Üí‚Č†‚Üí‚óá
         ; explicit use of ind-Absurd
         (őĽ (absurd A) (ind-Absurd absurd A))
         A
         dec‚Āľ
         x
         y
         x‚Č†y)))

  ; postulating the law of excluded middle
  (claim lem (ő† ((A U)) (‚ą® A (¬¨ A))))
  (define lem TODO)

  (claim ‚Č†‚Üí‚óá-classical
    (ő† ((A U)
        (x A)
        (y A))
       (‚Üí (‚Č† A x y) (‚óá A x y))))
  (define ‚Č†‚Üí‚óá-classical
    (őĽ (A x y x‚Č†y)
       (dec‚Āľ‚Üí‚Č†‚Üí‚óá
         A
         (őĽ (p) (lem (= A (car p) (cdr p))))
         x
         y
         x‚Č†y)))
#+end_src

* Deciders

But what about minimal Pie?  We've demonstrated that we can't prove
‚Č†‚Üí‚óá from decidable equality, but is there a /stronger/ notion of
decidable equality that holds in minimal Pie?  The short answer: yes.
In minimal pie, /we can't even prove that the obvious decider is
actually a decider./ That is, having a decider in minimal Pie (in the
sense that the obvious decider is, in fact, a decider) is a stronger
condition than admitting decidable equality.  The long answer: read
on, that's the point of the piece.

One direction of the claim in the previous paragraph is fairly easy:
if a predicate ūĚĎÉ has a decider, then it's decidable, even in minimal
Pie.  The proof: given ūĚĎ•, ask the decider if ūĚĎÉ(ūĚĎ•) or ¬¨ūĚĎÉ(ūĚĎ•).  We break
the proof up into two parts because working with ő£-types in Pie isn't
ergonomic.

#+begin_src
(claim decides‚ÜídecŠīĺ-helper
  (ő† ((A U)
      (f (‚Üí A Bool))
      (P (‚Üí A U))
      (x A))
     (‚Üí (‚ÜĒ (P x) (= Bool (f x) true))
        (Dec (P x)))))
(define decides‚ÜídecŠīĺ-helper
  (őĽ (_ f P x)
     (ind-Bool
       (f x)
       (őĽ (b)
          (‚Üí (‚ÜĒ (P x) (= Bool b true))
	     (Dec (P x))))
       (őĽ (prf)
          (left ((cdr prf) (same true))))
       (őĽ (prf)
          (right
	    (őĽ (px)
	       (explode-true=false
	         (symm ((car prf) px))
		 ‚ä•)))))))

(claim decider‚ÜídecŠīĺ
  (ő† ((A U)
      (P (‚Üí A U)))
     (‚Üí (Decider A P)
        (DecŠīĺ A P))))
(define decider‚ÜídecŠīĺ
  (őĽ (A P decider x)
     (decides‚ÜídecŠīĺ-helper
       A
       (car decider)
       P
       x
       ((cdr decider) x))))
#+end_src

The more difficult direction is to show that if ūĚĎÉ is decidable then it
has a decider.  Though difficult is not quite right.  The proof is
very natural: the obvious decider for ūĚĎÉ is a decider. But in minimal
Pie, /we can't prove this./

Let's break this into two observations: in minimal Pie, if we know the
value of the obvious decider on ūĚĎé, then we /can/ derive proofs of the
ūĚĎÉ(ūĚĎé) or ¬¨ūĚĎÉ(ūĚĎé), depending on the value.

#+begin_src
(claim p?=true‚Üíp
  (ő† ((A U)
      (P (‚Üí A U))
      (decŠīĺ (DecŠīĺ A P))
      (x A))
     (‚Üí (= Bool (? A P decŠīĺ x) true)
        (P x))))
(define p?=true‚Üíp
  (őĽ (_ P decŠīĺ x)
     (ind-Either
       (decŠīĺ x)
       (őĽ (e)
          (‚Üí (= Bool
	        (left? (P x) (¬¨ (P x)) e)
	        true)
             (P x)))
       (őĽ (px _) px)
       (őĽ (_ false=true)
          (explode-true=false
	    (symm false=true)
	    (P x))))))

(claim p?=false‚Üí¬¨p
  (ő† ((A U)
      (P (‚Üí A U))
      (decŠīĺ (DecŠīĺ A P))
      (x A))
     (‚Üí (= Bool
           (? A P decŠīĺ x)
	   false)
        (¬¨ (P x)))))
(define p?=false‚Üí¬¨p
  (őĽ (_ P decŠīĺ x)
     (ind-Either
       (decŠīĺ x)
       (őĽ (e)
          (‚Üí (= Bool
	        (left? (P x) (¬¨ (P x)) e)
		false)
             (¬¨ (P x))))
       (őĽ (_ true=false)
          (explode-true=false
	    true=false
	    (¬¨ (P x))))
       (őĽ (¬¨px _) ¬¨px))))
#+end_src

What we /can't/ do within minimal Pie is determine the value of the
decider itself given ūĚĎÉ(ūĚĎé) or ¬¨ūĚĎÉ(ūĚĎé), e.g., ūĚĎÉ(ūĚĎé) implies the ūĚĎÉ?(ūĚĎé) is
true given the principle of explosion, but this implication also
/implies/ the principle of explosion.  This ultimately comes down to
the fact that there isn't a whole lot we can do in the ¬¨ūĚĎÉ(ūĚĎé) branch of
the ūĚĎÉ-decidability invocation except explode it with our assumption
ūĚĎÉ(ūĚĎé).

#+begin_src lisp

(claim ind-‚ä•‚Üíp‚Üíp?=true
  (‚Üí (‚Üí ‚ä• (ő† ((A U)) A))
     (ő† ((A U)
         (P (‚Üí A U))
	 (decŠīĺ (DecŠīĺ A P))
	 (x A))
	(‚Üí (P x)
	   (= Bool
	      (? A P decŠīĺ x)
	      true)))))
(define ind-‚ä•‚Üíp‚Üíp?=true
  (őĽ (ind-‚ä• _ P decŠīĺ x px)
     (ind-Either
       (decŠīĺ x)
       (őĽ (e)
          (= Bool
	     (left? (P x) (¬¨ (P x)) e)
	     true))
       (őĽ (_) (same true))
       (őĽ (¬¨px)
          (ind-‚ä•
	    (¬¨px px)
	    (= Bool false true))))))

(claim ‚ü®p‚Üíp?=true‚ü©‚Üíind-‚ä•
  (‚Üí (ő† ((A U)
         (P (‚Üí A U))
	 (decŠīĺ (DecŠīĺ A P))
	 (x A))
	(‚Üí (P x)
	   (= Bool
	      (? A P decŠīĺ x)
	      true)))
     (‚Üí ‚ä• (ő† ((A U)) A))))
(define ‚ü®p‚Üíp?=true‚ü©‚Üíind-‚ä•
  (őĽ (p‚Üíp?=true absurd)
     (explode-true=false
       (symm
         (p‚Üíp?=true
           ‚ä§
           (őĽ (_) ‚ä§)
           (őĽ (_) (right (őĽ (_) absurd)))
           sole
           sole)))))

(claim ind-‚ä•‚Üí¬¨p‚Üíp?=false
  (‚Üí (‚Üí ‚ä• (ő† ((A U)) A))
     (ő† ((A U)
         (P (‚Üí A U))
	 (decŠīĺ (DecŠīĺ A P))
	 (x A))
	(‚Üí (¬¨ (P x))
	   (= Bool
	      (? A P decŠīĺ x)
	      false)))))
(define ind-‚ä•‚Üí¬¨p‚Üíp?=false
  (őĽ (ind-‚ä• _ P decŠīĺ x ¬¨px)
     (ind-Either
       (decŠīĺ x)
       (őĽ (e)
          (= Bool
	     (left? (P x) (¬¨ (P x)) e)
	     false))
       (őĽ (px)
          (ind-‚ä•
	    (¬¨px px)
	    (= Bool true false)))
       (őĽ (_) (same false)))))

(claim ‚ü®¬¨p‚Üíp?=false‚ü©‚Üíind-‚ä•
  (‚Üí (ő† ((A U)
         (P (‚Üí A U))
	 (decŠīĺ (DecŠīĺ A P))
	 (x A))
	(‚Üí (¬¨ (P x))
	   (= Bool
	      (? A P decŠīĺ x)
	      false)))
     (‚Üí ‚ä• (ő† ((A U)) A))))
(define ‚ü®¬¨p‚Üíp?=false‚ü©‚Üíind-‚ä•
  (őĽ (¬¨p‚Üíp?=false absurd)
     (explode-true=false
       (¬¨p‚Üíp?=false
         ‚ä§
	 (őĽ (_) ‚ä•)
	 (őĽ (_) (left absurd))
	 sole
	 (őĽ (absurd) absurd)))))
#+end_src

This inability to determine the value of the decider implies our
inability to prove that the obvious decider decides.

#+begin_src
(claim ind-‚ä•‚ÜídecŠīĺ‚Üídecides
  (‚Üí (‚Üí ‚ä• (ő† ((A U)) A))
     (ő† ((A U)
         (P (‚Üí A U))
	 (decŠīĺ (DecŠīĺ A P)))
	(Decides A (? A P decŠīĺ) P))))
(define ind-‚ä•‚ÜídecŠīĺ‚Üídecides
  (őĽ (ind-absurd A P decŠīĺ x)
     (cons
       (ind-‚ä•‚Üíp‚Üíp?=true
         ind-absurd
	 A
	 P
	 decŠīĺ
	 x)
       (p?=true‚Üíp
         A
	 P
	 decŠīĺ
	 x))))

(claim ind-‚ä•‚ÜídecŠīĺ‚Üídecider
  (‚Üí (‚Üí ‚ä• (ő† ((A U)) A))
     (ő† ((A U)
         (P (‚Üí A U))
	 (decŠīĺ (DecŠīĺ A P)))
	(Decider A P))))
(define ind-‚ä•‚ÜídecŠīĺ‚Üídecider
  (őĽ (ind-‚ä• A P decŠīĺ)
     (cons
       (? A P decŠīĺ)
       (ind-‚ä•‚ÜídecŠīĺ‚Üídecides
         ind-‚ä•
	 A
	 P
	 decŠīĺ))))

(claim ‚ü®decŠīĺ‚Üídecides‚ü©‚Üíind-‚ä•
  (‚Üí (ő† ((A U)
         (P (‚Üí A U))
	 (decŠīĺ (DecŠīĺ A P)))
	(Decides A (? A P decŠīĺ) P))
     (‚Üí ‚ä• (ő† ((A U)) A))))
(define ‚ü®decŠīĺ‚Üídecides‚ü©‚Üíind-‚ä•
  (őĽ (decŠīĺ‚Üídecides absurd)
     (explode-true=false
       (symm
         ((car
	    ((decŠīĺ‚Üídecides
	       ‚ä§
	       (őĽ (_) ‚ä§)
	       (őĽ (_) (right (őĽ (_) absurd))))
	      sole))
	    sole)))))
#+end_src

I'm under the impression that it's also impossible to prove that
decidability implies having /any/ decider in minimal Pie, but this is
out of reach if we want to internalize this fact as we've been
doing. We need some handle on what the decider is to prove anything
about it.

Getting to the point: having an equality decider is a stronger than
admitting decidable equality in minimal Pie. This makes it a candidate
condition from which we might prove distinguishability of unequals.
But, alas, it's not sufficient.  Its easy to build an equality decider
for the ~Trivial~ type, so we can use our artificial negation proof
trick again.

#+begin_src lisp
(claim ‚ü®decider‚Āľ‚Üí‚Č†‚Üí‚óá‚ü©‚Üíind-‚ä•
  (‚Üí (ő† ((A U)
         (decider‚Āľ (Decider‚Āľ A))
	 (x A)
	 (y A))
	(‚Üí (‚Č† A x y) (‚óá A x y)))
     (‚Üí ‚ä• (ő† ((A U)) A))))
(define ‚ü®decider‚Āľ‚Üí‚Č†‚Üí‚óá‚ü©‚Üíind-‚ä•
  (őĽ (decider‚Āľ‚Üí‚Č†‚Üí‚óá absurd)
     (‚óá‚Üíexplode‚Āľ
       Trivial
       sole
       sole
       (decider‚Āľ‚Üí‚Č†‚Üí‚óá
         Trivial
	 (cons
	   (őĽ (_ _) true)
	   (őĽ (p)
  	     (cons
  	       (őĽ (_) (same true))
  	       (őĽ (_) (same sole)))))
	 sole
	 sole
         ; artifical negation proof
	 (őĽ (_) absurd))
       (same sole))))
#+end_src

Our quest continues.

* Distinguishability

But first, a side quest. Let's consider another definition which
implies decidable equality, and seems promising.  We'll say that a
type admits *complete distinguishability* if all of its values are
equal or distinguishable.

#+begin_src
(claim Distinguishability (‚Üí U U))
(define Distinguishability
  (őĽ (A)
     (ő† ((x A)
         (y A))
	(‚ą® (= A x y)
	   (‚óá A x y)))))
#+end_src

It shouldn't be too surprising that having an equality decider is
equivalent to admitting complete distinguishability in vanilla Pie
(because of ‚óá‚Üí‚Č†).  What's surprising (at least to me) is that this
also holds in minimal Pie, i.e., /the ability to construct an
equality decider from complete distinguishability does not depend on
the principle explosion./ In this sense, complete distinguishability
is the "correct" lowering of decidable equality into minimal Pie if we
want to be able to derive equality deciders.

As usual, one direction is easier than the other. If we have an
equality decider, we can use it to distinguish unequals.

#+begin_src
(claim =true‚ą®=false
  (ő† ((b Bool))
     (‚ą® (= Bool b true)
        (= Bool b false))))
(define =true‚ą®=false
  (őĽ (b)
     (ind-Bool
       b
       (őĽ (b)
          (‚ą® (= Bool b true)
             (= Bool b false)))
      (left (same true))
      (right (same false)))))

(claim decider‚Āľ‚Üídist
  (ő† ((A U))
     (‚Üí (Decider‚Āľ A)
        (Distinguishability A))))
(define decider‚Āľ‚Üídist
  (őĽ (A decider‚Āľ x y)
     (ind-Either
       (=true‚ą®=false ((car decider‚Āľ) x y))
       (őĽ (_)
          (‚ą® (= A x y)
	     (‚óá A x y)))
       (őĽ (fxy=true)
          (left
	    ((cdr ((cdr decider‚Āľ) (cons x y))) fxy=true)))
       (őĽ (fxy=false)
          (right
	    (cons
	      ((car decider‚Āľ) x)
	      (cons
	        ((car ((cdr decider‚Āľ) (cons x x))) (same x))
		fxy=false)))))))
#+end_src

To derive an equality decider from complete distinguishability, it'll
be convenient to hand roll a new obvious decider, the analogous one
for complete distinguishability.  We can prove that this decider is,
in fact, a decider by taking advantage of the ambient
distinguishability proof, which we can leverage to avoid using
explosion.

#+begin_src
(claim ==
  (ő† ((A U))
     (‚Üí (Distinguishability A) A A Bool)))
(define ==
  (őĽ (A dist x y)
     (left?
       (= A x y)
       (‚óá A x y)
       (dist x y))))

(claim dist‚Üí=‚Üí==true
  (ő† ((A U)
      (dist (Distinguishability A))
      (x A)
      (y A))
     (‚Üí (= A x y)
        (= Bool
	   (== A dist x y)
	   true))))
(define dist‚Üí=‚Üí==true
  (őĽ (A dist x y x=y)
     (replace
       x=y
       (őĽ (a)
          (= Bool
	     (== A dist x a)
	     true))
       (ind-Either
         (dist x x)
	 (őĽ (e)
	    (= Bool
	       (left?
	         (= A x x)
		 (‚óá A x x)
		 e)
	       true))
	 (őĽ (_) (same true))
	 (őĽ (x‚óáx)
	    (trans
	      ; false = f x
	      (symm (cdr (cdr x‚óáx)))
	      ; f x = true
	      (car (cdr x‚óáx))))))))

(claim dist‚Üí==true‚Üí=
  (ő† ((A U)
      (dist (Distinguishability A))
      (x A)
      (y A))
     (‚Üí (= Bool
	   (== A dist x y)
	   true)
	(= A x y))))
(define dist‚Üí==true‚Üí=
  (őĽ (A dist x y)
     (ind-Either
       (dist x y)
       (őĽ (e)
          (‚Üí (= Bool
	       (left?
	         (= A x y)
	         (‚óá A x y)
	         e)
	       true)
	     (= A x y)))
       (őĽ (x=y _) x=y)
       (őĽ (_ false=true)
          (explode-true=false
	    (symm false=true)
	    (= A x y))))))

(claim dist‚Üídecider‚Āľ
  (ő† ((A U))
     (‚Üí (Distinguishability A)
        (Decider‚Āľ A))))
(define dist‚Üídecider‚Āľ
  (őĽ (A dist)
     (cons
       (== A dist)
       (őĽ (p)
          (cons
            (dist‚Üí=‚Üí==true A dist (car p) (cdr p))
            (dist‚Üí==true‚Üí= A dist (car p) (cdr p)))))))
#+end_src

This, of course, gets us nowhere on our quest to find a condition that
allows use to distinguish unequals, but its a digression through which
I couldn't help but take a detour.

* Strong Deciders

There are likely far more intermediate definitions of decidable
equality we could look at, but let's get to the punchline.  Looking
back, our inability to work with the obvious decider in minimal Pie
came from our inability to derive equalities for its output values.  A
minimal definition of decidability should give us this power so we
don't need to appeal to explosion.

We'll say that a function ūĚĎď is a *strong decider* for the predicate ūĚĎÉ
if ūĚĎÉ(ūĚĎé) implies ūĚĎď(ūĚĎé) is true and ¬¨ūĚĎÉ(ūĚĎé) implies ūĚĎď(ūĚĎé) is false.

#+begin_src
(claim Strong-Decides
  (ő† ((A U)
      (f (‚Üí A Bool))
      (P (‚Üí A U)))
     U))
(define Strong-Decides
  (őĽ (A f P)
     (ő† ((x A))
        (‚ąß (‚Üí (P x) (= Bool (f x) true))
           (‚Üí (¬¨ (P x)) (= Bool (f x) false))))))

(claim Strong-Decider
  (ő† ((A U)
      (P (‚Üí A U)))
     U))
(define Strong-Decider
  (őĽ (A P)
     (ő£ ((f (‚Üí A Bool)))
        (Strong-Decides A f P))))

(claim Strong-Decides‚āā
  (ő† ((A U)
      (B U)
      (f (‚Üí A B Bool))
      (P (‚Üí A B U)))
     U))
(define Strong-Decides‚āā
  (őĽ (A B f P)
     (Strong-Decides
       (Pair A B)
       (uncurry A B Bool f)
       (UncurryŠīĺ A B P))))

(claim Strong-Decider‚āā
  (ő† ((A U)
      (B U)
      (P (‚Üí A B U)))
     U))
(define Strong-Decider‚āā
  (őĽ (A B P)
     (ő£ ((f (‚Üí A B Bool)))
        (Strong-Decides‚āā A B f P))))

(claim Strong-Decides‚Āľ
  (ő† ((A U)
      (f (‚Üí A A Bool)))
     U))
(define Strong-Decides‚Āľ
  (őĽ (A f)
     (Strong-Decides‚āā
       A
       A
       f
       (őĽ (x y) (= A x y)))))

(claim Strong-Decider‚Āľ (‚Üí U U))
(define Strong-Decider‚Āľ
  (őĽ (A)
     (ő£ ((f (‚Üí A A Bool)))
        (Strong-Decides‚Āľ A f))))
#+end_src

Having a strong decider is equivalent to having a decider in vanilla
Pie, but we can see the "stress" this new definition puts on the
minimal Pie (in the sense that we're pushing against the boundary of
minimal and vanilla Pie).  The only thing that blocks the equivalence
in minimal Pie is our inability to prove something very simple: a
Boolean value that not true is false.  It may be worth noting that
this principle also has similarities to semi-classical principles like
the [[https://en.wikipedia.org/wiki/Limited_principle_of_omniscience][limited principle of omnipotence]].

#+begin_src
(claim ind-‚ä•‚Üí‚Č†true‚Üí=false
  (‚Üí (‚Üí ‚ä• (ő† ((A U)) A))
     (ő† ((b Bool))
        (‚Üí (‚Č† Bool b true)
	   (= Bool b false)))))
(define ind-‚ä•‚Üí‚Č†true‚Üí=false
  (őĽ (ind-‚ä• b b‚Č†true)
     (ind-Either
       (=true‚ą®=false b)
       (őĽ (_) (= Bool b false))
       (őĽ (b=true)
          (ind-‚ä•
	    (b‚Č†true b=true)
	    (= Bool b false)))
       (őĽ (b=false) b=false))))

(claim ‚ü®‚Č†true‚Üí=false‚ü©‚Üíind-‚ä•
  (‚Üí (ő† ((b Bool))
        (‚Üí (‚Č† Bool b true)
	   (= Bool b false)))
     (‚Üí ‚ä• (ő† ((A U)) A))))
(define ‚ü®‚Č†true‚Üí=false‚ü©‚Üíind-‚ä•
  (őĽ (‚Č†true‚Üí=false absurd)
     (explode-true=false
       (‚Č†true‚Üí=false
         true
	 (őĽ (_) absurd)))))

(claim ind-‚ä•‚Üídecides‚Āľ‚Üístrong-decides‚Āľ
  (‚Üí (‚Üí ‚ä• (ő† ((A U)) A))
     (ő† ((A U)
         (f (‚Üí A A Bool)))
        (‚Üí (Decides‚Āľ A f)
           (Strong-Decides‚Āľ A f)))))
(define ind-‚ä•‚Üídecides‚Āľ‚Üístrong-decides‚Āľ
  (őĽ (ind-‚ä• A f decides‚Āľ p)
     (cons
       (car (decides‚Āľ p))
       (őĽ (x‚Č†y)
          (ind-‚ä•‚Üí‚Č†true‚Üí=false
            ind-‚ä•
            (f (car p) (cdr p))
            (őĽ (fxy=true)
               (x‚Č†y ((cdr (decides‚Āľ p)) fxy=true))))))))

(claim ‚ü®decides‚Āľ‚Üístrong-decides‚Āľ‚ü©‚Üíind-‚ä•
  (‚Üí (ő† ((A U)
         (f (‚Üí A A Bool)))
        (‚Üí (Decides‚Āľ A f)
           (Strong-Decides‚Āľ A f)))
     (‚Üí ‚ä• (ő† ((A U)) A))))
(define ‚ü®decides‚Āľ‚Üístrong-decides‚Āľ‚ü©‚Üíind-‚ä•
  (őĽ (decides‚Āľ‚Üístrong-decides‚Āľ absurd)
     (explode-true=false
       ((cdr
          (decides‚Āľ‚Üístrong-decides‚Āľ
            ‚ä§
 	    (őĽ (_ _) true)
 	    (őĽ (_)
 	       (cons
 	         (őĽ (_) (same true))
 	         (őĽ (_) (same sole))))
            (cons sole sole)))
         (őĽ (_) absurd)))))
#+end_src

Finally, having a strong decider is not quite stronger than having a
decider in minimal Pie, but it is when taken in tandem with decidable
equality.

#+begin_src
(claim dec‚Āľ‚Üístrong-decider‚Āľ‚Üídecider‚Āľ
  (ő† ((A U))
     (‚Üí (Dec‚Āľ A)
        (Strong-Decider‚Āľ A)
        (Decider‚Āľ A))))
(define dec‚Āľ‚Üístrong-decider‚Āľ‚Üídecider‚Āľ
  (őĽ (A dec‚Āľ strong-decider‚Āľ)
     (cons
       (car strong-decider‚Āľ)
       (őĽ (p)
         (cons
           (car ((cdr strong-decider‚Āľ) p))
           (őĽ (fxy=true)
              (ind-Either
	        (dec‚Āľ p)
	        (őĽ (_) (= A (car p) (cdr p)))
	        (őĽ (x=y) x=y)
	        (őĽ (x‚Č†y)
	           (explode-true=false
	             (trans
		       ; true = f (car p) (cdr p)
		       (symm fxy=true)
		       ; f (car p) (cdr p) = false
		       ((cdr ((cdr strong-decider‚Āľ) p)) x‚Č†y))
		     (= A (car p) (cdr p)))))))))))
#+end_src
In particular, having a strong decider is strictly stronger than
having a decider in the /paraconsistent/ variant of Pie (i.e., with
excluded middle and without explosion).

* Conclusions

Despite the circuitous nature of this story, the ending is simple: in
minimal Pie, if a type ūĚźī has a strong equality decider, then it has
distinguishable unequals.

#+begin_src
(claim strong-decider‚Āľ‚Üí‚Č†‚Üí‚óá
  (ő† ((A U)
      (strong-decider‚Āľ (Strong-Decider‚Āľ A))
      (x A)
      (y A))
     (‚Üí (‚Č† A x y) (‚óá A x y))))
(define strong-decider‚Āľ‚Üí‚Č†‚Üí‚óá
  (őĽ (A strong-decider‚Āľ x y x‚Č†y)
     (cons
       ((car strong-decider‚Āľ) x)
       (cons
         ((car ((cdr strong-decider‚Āľ) (cons x x))) (same x))
	 ((cdr ((cdr strong-decider‚Āľ) (cons x y))) x‚Č†y)))))
#+end_src

And this is certainly one of those cases where the journey is worth
more than the destination.  The final definition seems /right/, in the
sense that the proof uses the data its given exactly as you would
expect. There's a satisfying beauty to it, like all the pieces go where
they should.  But the true value of this exercise comes from
recognizing that having strong deciders sits on a spectrum of
decidable equality that is not really all that visible in vanilla Pie.

Generally speaking, I believe that examining the minimal fragments of
constructive logics in this reverse-mathematical fashion can reveal
some pretty interesting structures in constructive proofs.  Or maybe
it just scratches in itch for the proof-twiddlers among us.

One last thing. It's perhaps worth giving one final definition:

#+begin_src
(claim Very-Strong-Decides
  (ő† ((A U)
      (f (‚Üí A Bool))
      (P (‚Üí A U)))
     U))
(define Very-Strong-Decides
  (őĽ (A f P)
     (ő† ((x A))
        (‚ąß (‚ÜĒ (P x) (= Bool (f x) true))
	   (‚ÜĒ (¬¨ (P x)) (= Bool (f x) false))))))
#+end_src

If you're feeling explosion conscious, having a very strong decider in
this sense seems to be the "right" way of capturing decidable
equality.  It's ultimately just an amalgamation of a strong decider
and a decider, so it's equivalent to decidable equality in vanilla
Pie.  Its only curiosity is that there's no need to require in the
definition

#+begin_quote
(‚Üí (= Bool (f x) false) (¬¨ (P x)))
#+end_quote

because this is implied (in minimal Pie) by the other three
implications.  But, I'd choose an unnecessary assumption over a lack
of symmetry any day.

/July 1, 2025/
