#+title: 2026 in 52 albums
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../nmmull.css" />
#+OPTIONS: html-style:nil H:1 num:nil toc:nil
#+HTML_LINK_HOME: http://nmmull.github.io
The concept's pretty simple.  One album per week, not necessarily my
favorite album of the week, not necessarily a new album, just one that
I listened to and liked.
1. *Snocaps* by Snocaps

   Unapologetically catchy, produced enough to not feel like a demo
   tape, but not so much that it has the sometimes-cloying polish of
   recent Waxahatchee.  "Angel Wings" is the first ear-worm in a while
   I've enjoyed having.

2. *With Greg from Deerhoof* by Serengeti

   An unexpected but natural collaboration, the 17 minute ad-hoc live
   session "I Got Your Password" is unreal.  This album has been on my
   listening queue for years, but I think aptly captures 2026's
   off-the-bat absurdities.

3. *Trio!* by Dabin Ryu

   Dabin Ryu has classical-pianist-energy.  The opener "Vertigo" has
   Ólafsson precision (sub Bach for post-bop) and the intro of "In the
   Land of Oo-Bla-Dee" plays like a Prokofiev piano sonata.  Also goes
   without saying, Joe Martin (bass) and Johnathan Blake (drums) hold
   their own, and have plenty of their own shining moments.

4. *On A Friday Evening* by the Bill Evans Trio

   Every so often, I need to listen to Evans.  And after week one of
   the spring semester, I needed something with quiet strength.  Evans
   for me straddles the Burkian beauty-sublime divide, the decisions
   he makes with regard to phrasing seem written in the clouds.  I
   also kinda love Eddie Gomez's buzzy bass in this recording, it
   brings out the lightness and occasional humor of it all.
