#+title: 2026 in 52 albums
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../nmmull.css" />
#+OPTIONS: html-style:nil H:1 num:nil toc:nil
#+HTML_LINK_HOME: http://nmmull.github.io
The concept's pretty simple.  One album per week, not necessarily my
favorite album of the week, not necessarily a new album, just one that
I listened to and liked.
1. *Snocaps* by Snocaps

   Unapologetically catchy, produced enough to not feel like a demo
   tape, but not so much that it has the sometimes-cloying polish of
   recent Waxahatchee.  "Angel Wings" is the first ear-worm in a while
   I've enjoyed having.

2. *With Greg from Deerhoof* by Serengeti

   An unexpected but natural collaboration, the 17 minute ad-hoc live
   session "I Got Your Password" is unreal.  This album has been on my
   listening queue for years, but I think aptly captures 2026's
   off-the-bat absurdities.

3. *Trio!* by Dabin Ryu

   Dabin Ryu has classical-pianist-energy.  The opener "Vertigo" has
   Ólafsson precision (sub Bach for post-bop) and the intro of "In the
   Land of Oo-Bla-Dee" plays like a Prokofiev piano sonata.  Also goes
   without saying, Joe Martin (bass) and Johnathan Blake (drums) hold
   their own, and have plenty of their own shining moments.

4. *On A Friday Evening* by the Bill Evans Trio

   Every so often, I need to listen to Evans.  And after week one of
   the spring semester, I needed something with quiet strength.  Evans
   for me straddles the Burkian beauty-sublime divide, the decisions
   he makes with regard to phrasing seem written in the clouds.  I
   also kinda love Eddie Gomez's buzzy bass in this recording, it
   brings out the lightness and occasional humor of it all.

5. *Magnetism* by the Kali Malone + Drew McDowall

   Ambient can sometimes be inscrutable (at least for me) but
   occasionally you get lucky with the context in which you first hear
   a piece of ambient.  I was in a weird place in my life, staring out
   at a pond on a cool fall day while my car was getting serviced.
   The emergent overtones and relentlessly compressed bass drones of
   the synthesizer just worked for this scene and headspace.

6. *PROTO* by Holly Herndon

   With all that's going on in the AI-sphere, this 2019 AI-music
   experiment feels almost quiant. It's a marked departure from
   Herndon's previous two albums; when listening to *Movement* and
   *Platform*, one has the feeling that every synth began life as a
   sine wave and was molded to fit its aural purpose, wrestled into
   submission and imbued with a sense of the primordial.  In *PROTO*,
   Herndon takes the voice as the starting point, and uses AI to aid
   the molding, a more powerful tool for a less giving medium.  This
   is done to great effect, but I believe falls into the trap of many
   early-AI projects: AI is used in the way that reverb is used in
   recording, it creates "aura" but muddles personality (compare
   Casals and Ma on the cello suites).  The AI of it all pushes
   Herndon towards "the middle", welcoming more than usual (not
   unflattering) comparisons─I get flavors of Oneohtrix Point Never,
   Caroline Shaw, Julia Holter, Purity Ring, and it's hard not to
   think of Imogen Heap, at least for folks listening to music in the
   aughts.  Taken as an experiment (as I think it's intended) *PROTO*
   is ground-breaking, and I can't think of anyone I'd rather tackle
   the AI-music puzzle.
