#+title: A Pedagogy Reading Group
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../globalStyle.css" />
#+OPTIONS: html-style:nil H:3 toc:nil num:nil
This is the landing page for an informal reading group on pedagogy at
Boston University.  We meet a couple times a semester to discuss
anything and everything pedagogy and teaching.  The intended audience
is anyone teaching (or who will teach) courses at BU who wants to
think more about their practice.

If you want to be added to the email list for this group (or if you
want to be removed from the email list), please send a message to
~nmmull at bu dot edu~.  *If you're interesting in leading a
discussion* on a paper/book chapter that you read, or just a discussion
of the form "this is what I've been thinking about recently", please
send an message.

* Fall 2024

For the fall 2024 semester we'll be meeting on *Fridays 12-1PM in CDS 950*.
See the sections below for dates and topics.
** 2024-10-04 SIGCE 2024 Playlist
+ *discussion leader:* Nathan Mull
+ *outline:* There were a bunch of interesting-looking papers out of
  [[https://sigcse2024.sigcse.org][SIGCE]] this year, I'd like to chat about some of the ones that caught
  my eye.  The two main papers I'd like to discuss are
  + [[https://dl.acm.org/doi/10.1145/3626252.3630846][Experiences of Undergraduate Computer Science Students Living with Mental Health Conditions]]
  + [[https://dl.acm.org/doi/10.1145/3626252.3630953][Transforming Grading Practices in the Computing Education Community]]
  They're kind of hard to read, but I'd like to more directly confront
  the challenges that students face outside of the courses I teach.  I
  think there's a lot of space here to talk about our experiences,
  failures, and solutions (in any field).

  We likely won't have time to discuss them but I also want to include
  these papers, which are more specific to computer science.
  + [[https://dl.acm.org/doi/10.1145/3626252.3630904][Participatory Governance in the Computer Science Theory Classroom]]
  + [[https://dl.acm.org/doi/abs/10.1145/3626252.3630871][How We Manage an Army of Teaching Assistants: Experience Report on Scaling a CS1 Course]]
  Though not perfect, I think they offer potential solutions to
  creating more accessible computer science courses, even at scale.
+ *Zoom link:* /past/
** 2024-11-08 Trauma-Informed Teaching
+ *discussion leader:* Tori Lee
+ *outline:* We'll discuss trauma-informed teaching and mental health
  and try to take away some practical/actionable steps from our
  readings for things we can implement into spring courses, e.g.,
  small steps we can take in planning our syllabi and assignments
  (acknowledging that CS courses typically don’t actually teach
  /about/ sexual assault, but certainly teach to students who have
  experienced it).
+ *Zoom link:* [[https://bostonu.zoom.us/j/96468715816?pwd=lzNk2LFUiCVPcFF3ihXVcvrnHbENye.1][link]]
** 2024-12-06 Microintervention Strategies
+ *discussion leader:* Anna Ward
+ *outline:* We'll look at the first three chapters of
  [[https://www.wiley.com/en-us/Microintervention+Strategies%3A+What+You+Can+Do+to+Disarm+and+Dismantle+Individual+and+Systemic+Racism+and+Bias-p-9781119769989][Microintervention Strategies]] and discuss how these strategies can be
  applied to interacting with students and designing material
+ *Zoom link:* [[https://bostonu.zoom.us/j/98846086217?pwd=mxxFfQblPeXjCOUcBai44HastEaRoT.1][link]]
